
version: "3"
services:


  postgres:
    image: sameersbn/postgresql:9.5-3
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=merlin
      - DB_PASS=merlin
      - DB_NAME=merlin
